### ISSUE TITLE
[Enhancement] Suggested to refine the document

### ISSUE THREAD

**Issue by ghost** [MeoProject/lx-music-api-server#17]
Plz complete introduction of files and explicit what can be modified, THANK U

**Comment by helloplhm-qwq** [comment]
I will do that, but please wait for my winter holiday plz
thanks
Are you foreigners? If that, maybe I will add i18n support for logs in the coming winter holiday()

**Comment by helloplhm-qwq** [comment]
> I will do that, but please wait for my winter holiday plz thanks Are you foreigners? If that, maybe I will add i18n support for logs in the coming winter holiday()

about 15 days before the Chinese new year(the Sprint Festival), maybe in Jan 25th
I touched by mistake(close with comment) just now, so i reopened this

**Comment by gkcoll** [comment]
Wow, you replied so fast! Thank you for your support.
I am not a foreigner, I am just a student in domestic senior high (Senior 2). Post in English on REAL Internet is just my habit (it's necessary to point that for native English speakers, we are foreigners).
I take a good view to your work, young man!

**Comment by helloplhm-qwq** [comment]
> Wow, you replied so fast! Thank you for your support. I am not a foreigner, I am just a student in domestic senior high (Senior 2). Post in English on REAL Internet is just my habit (it's necessary to point that for native English speakers, we are foreigners). I take a good view to your work, young man!

`it's necessary to point that for native English speakers, we are foreigners` yeah, of course I know that, but in such situation(this repo), the `foreigners` should be defined as anyone whose native language is not Chinese

**Comment by helloplhm-qwq** [comment]
I will work on this repo, until it's completed for me(add search, info, mv, album and so on for ALL the music sources)
I am one of the contributor of the official LX Music repo so I will (nothing to say)

**Comment by helloplhm-qwq** [comment]
All right, the document has started writing, please see the `docs` and `gh-pages` branch, or visit <https://apidoc.zcmonety.xyz>

**Comment by ikun0014** [comment]
@helloplhm-qwq All right.The account is deleted.
