### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './logs/print.log'

### ISSUE THREAD

**Issue by Sjxooooooooooooooooooooooooooo** [MeoProject/lx-music-api-server#64]
不知道咋回事，刚运行就这样了

**Comment by helloplhm-qwq** [comment]
@Sjxooooooooooooooooooooooooooo 日志文件夹创建失败了

**Comment by Sjxooooooooooooooooooooooooooo** [comment]
哦，后来知道是因为权限没给足，谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月18日(星期四) 晚上11:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MeoProject/lx-music-api-server] FileNotFoundError: [Errno 2] No such file or directory: &#39;./logs/print.log&#39; (Issue #64)














 
@Sjxooooooooooooooooooooooooooo 日志文件夹创建失败了
