### ISSUE TITLE
关于js音源文件明文和加密

### ISSUE THREAD

**Issue by LookStars** [MeoProject/lx-music-api-server#65]
大佬们分享的js音源用txt打开都是一群乱码，而用该项目生成的示例js音源是明文的，有什么办法可以改成像大佬们一样的乱码的样式吗，因为也想分享音源

**Comment by helloplhm-qwq** [comment]
@LookStars 用js混淆工具混淆一下就可以了

**Comment by helloplhm-qwq** [comment]
@LookStars @dependabot close

**Comment by LookStars** [comment]
谢谢
