### ISSUE TITLE
支持自定义音源

### ISSUE THREAD

**Issue by yao521521** [MeoProject/lx-music-api-server#77]
请问大佬以后能否会支持自定义音源的解析，就像六因音源一样导入之后，解析出url连接返回，目前感觉想听的歌曲解析出来的连接都需要会员解锁😂

**Comment by ikun0014** [comment]
@yao521521 ？？？？？？？？？？？？

**Comment by ikun0014** [comment]
@yao521521 你说什么玩意

**Comment by yao521521** [comment]
就是通过python解析自定义音源然后得到自定义音源的连接，然后返回

**Comment by ikun0014** [comment]
只能说一开始就实现了谁让你不看配置文件的😡

**Comment by ikun0014** [comment]
建议好好看看

**Comment by yao521521** [comment]
好的好的，我看一下😂

**Comment by LizFun** [comment]
> 建议好好看看

配置项叫啥也大佬，找了一宿没找到 T_T
